spring:
  servlet:
    multipart:
      max-file-size: 10MB #最大文件
      max-request-size: 10MB #最大文件请求大小
      enabled: true # 关闭 multipart 支持
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  # 定义日期格式
    time-zone: GMT+8  # 定义时区，避免时间偏差
  devtools:
    restart:
      enabled: true
      poll-interval: 1000  # 检查间隔1秒
      quiet-period: 500    # 安静期0.5秒
      exclude: "static/**,templates/**,**.json"
    livereload:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # FreeMarker 配置
  freemarker:
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      time_zone: GMT+8
      output_format: HTML
    template-loader-path: classpath:/templates/ # 模板存放路径
    suffix: .ftl # 模板文件后缀
    cache: false # 开发时禁用缓存，便于调试
    charset: UTF-8 # 模板编码
    content-type: text/html # 响应内容类型
    check-template-location: true # 检查模板路径是否存在
    expose-request-attributes: true # 允许模板访问请求属性
    expose-session-attributes: true # 允许模板访问会话属性
    expose-spring-macro-helpers: true # 支持 Spring 的 FreeMarker 宏
  datasource:
    url: jdbc:mysql://localhost:3306/tinynote?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
#  sql:
#    init:
#      schema-locations: classpath:db/schema-mysql.sql
#      data-locations: classpath:db/data-mysql.sql
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug

projectName: TinyNode
upload:
  allowedextensions: jpg,png,gif,jpeg
