spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # FreeMarker 配置
  freemarker:
    template-loader-path: classpath:/templates/ # 模板存放路径
    suffix: .ftl # 模板文件后缀
    cache: false # 开发时禁用缓存，便于调试
    charset: UTF-8 # 模板编码
    content-type: text/html # 响应内容类型
    check-template-location: true # 检查模板路径是否存在
    expose-request-attributes: true # 允许模板访问请求属性
    expose-session-attributes: true # 允许模板访问会话属性
    expose-spring-macro-helpers: true # 支持 Spring 的 FreeMarker 宏
  datasource:
    url: jdbc:mysql://localhost:3306/tinynote?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      schema-locations: classpath:db/schema-mysql.sql
#      data-locations: classpath:db/data-mysql.sql
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug

