spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/tinynote2?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      time_zone: GMT+8
    template-loader-path: classpath:/templates/ # 模板存放路径
    suffix: .ftl # 模板文件后缀
    cache: true # 模版缓存
    charset: UTF-8 # 模板编码
    content-type: text/html # 响应内容类型
    check-template-location: true # 检查模板路径是否存在
    expose-request-attributes: true # 允许模板访问请求属性
    expose-session-attributes: true # 允许模板访问会话属性
    expose-spring-macro-helpers: true # 支持 Spring 的 FreeMarker 宏






